### ISSUE TITLE
Title Screen /w High Score

### ISSUE THREAD

**Issue by Striderzet** [osmanhajiyev/matchGame-iOS#1]
Game needs a Start / Title screen where players best score is displayed.

**Comment by osmanhajiyev** [comment]
Very good idea, Tony!!

**Comment by Striderzet** [comment]
You will need to do this before i can work on number 2 for you have all of the graphics for it.

**Comment by osmanhajiyev** [comment]
I included all the graphics in the assets folder. It is in the matchGame/Assets.xcassets folder. To access the graphics, go to Xcode and open the project as an Xcode project, and you will have all the assets, graphics, background in your assets folder. Let me know if you have any questions.

**Comment by Striderzet** [comment]
Ok, I will take a look at #1 and #2 and test them. If all is well with the enhancements, I will create one pull request for both.

**Comment by osmanhajiyev** [comment]
Merged your pull request! Good job Striderzet!

**Comment by osmanhajiyev** [comment]
Feel free to add any more enhancements or changes!
