### ISSUE TITLE
Game Over /w options

### ISSUE THREAD

**Issue by Striderzet** [osmanhajiyev/matchGame-iOS#2]
The" Game Over" alert should either be a splash screen or a more detailed alert where:

- Current score is displayed as compared to saved High Score
- Option to restart game (instead of clicking restart in game screen after alert is dismissed) or to go back to title screen (if added)

**Comment by osmanhajiyev** [comment]
Very good idea and please feel free to reach out to me, we can collaborate on this project together if you want and we can discuss the collaboration!

**Comment by Striderzet** [comment]
These have been added and tested. Is it you that needs to create the pull request or do I? I am new to this.

**Comment by osmanhajiyev** [comment]
Approved and merged! Good job!
